stages:
  - test
  - build

run_tests:
  stage: test
  image: python:3.9-slim
  before_script:
    - apt-get update && apt-get install -y make
    - pip install -r src/requirements.txt
  script:
    - make test

build_image:
  stage: build
  image: docker:28.3.3
  services:
    - docker:28.3.3-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin
  script:
    - docker build -t $REGISTRY_USER/assignmnety_22177669d:step4 .
    - docker push $REGISTRY_USER/assignmnety_22177669d:step4
