stages:
  - build
  - push

variables:
  DOCKER_HUB_USERNAME: "rimishghimire"
  DOCKER_HUB_PASSWORD: "your_dockerhub_password"
  IMAGE_NAME: "rimishghimire/assignment_22177669d:step3"

before_script:
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin

build:
  stage: build
  script:
    - docker build -t $IMAGE_NAME .

push:
  stage: push
  script:
    - docker push $IMAGE_NAME
