variables:
  IMAGE_NAME: "rimishghimire/assignment_22177669d"
  IMAGE_TAG: "step5"

run_tests:
  image: python:3.9-slim
  before_script:
    - apt-get update && apt-get install -y make
  script:
    - make test

build_image:
  stage: build
  image: docker:28.3.3
  services:
    - docker:28.3.3-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
