stages:
  - build
  
build_image:
  stage: build
  image: docker:28.3.3
  services:
    - docker:28.3.3-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375/
    IMAGE_NAME: rimishghimre/assignmnety_22177669d
    IMAGE_TAG: step3
  before_script:
    - docker login -u "<YOUR_USERNAME>" -p "<YOUR_PASSWORD>"
  script:
    - echo "docker build -t $IMAGE_NAME:$IMAGE_TAG ."
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - echo "docker push $IMAGE_NAME:$IMAGE_TAG"
    - docker push $IMAGE_NAME:$IMAGE_TAG
