stages:
  - test
  - build

run_tests:
  stage: test
  image: python:3.9-slim
  before_script:
    - apt-get update && apt-get install -y make
    - pip install -r src/requirements.txt
  script:
    - make test

build_image:
  stage: build
  image: docker:28.3.3
  services:
    - docker:28.3.3-dind
  variables:
    DOCKER_HOST: tcp://docker:2375/   # Required for DinD
    DOCKER_TLS_CERTDIR: ""             # Disable TLS to avoid connection issues
    IMAGE_TAG: $REGISTRY_USER/assignmnety_22177669d:step5-a1b2c3d
  before_script:
    - echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin
  script:
    - echo "docker build -t $IMAGE_TAG ."
    - docker build -t $IMAGE_TAG .
    - echo "docker push $IMAGE_TAG"
    - docker push $IMAGE_TAG
only:
    - main