stages:
  - build
  - test
  - deploy

# -----------------------------
# Step 2: Build job (optional simulation)
# -----------------------------
build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

# -----------------------------
# Step 2: Unit test job (optional)
# -----------------------------
unit-test-job:
  stage: test
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - sleep 60
    - echo "Code coverage is 90%"

# -----------------------------
# Step 2: Lint test job (optional)
# -----------------------------
lint-test-job:
  stage: test
  script:
    - echo "Linting code... This will take about 10 seconds."
    - sleep 10
    - echo "No lint issues found."

# -----------------------------
# Step 3 → 5: Build & push Docker image
# -----------------------------
docker-build-job:
  stage: deploy
  image: docker:28.3.3
  services:
    - docker:28.3.3-dind
  variables:
    DOCKER_TLS_CERTDIR: ""                   # Disable TLS for DinD
    DOCKER_HOST: tcp://docker:2375/          # Docker-in-Docker host
    IMAGE_NAME: rimishghimre/assignmnety_22177669d
    IMAGE_TAG: step5-a1b2c3d                  # Change manually per assignment step
  before_script:
    - echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin
  script:
    - echo "docker build -t $IMAGE_NAME:$IMAGE_TAG ."
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - echo "docker push $IMAGE_NAME:$IMAGE_TAG"
    - docker push $IMAGE_NAME:$IMAGE_TAG
    - echo "My name is Riya Ghimire and my student id is 22177669"
